### ISSUE TITLE
Nonresident Alien 的 Capital Gain / Loss 应属于 Not Effectively Connected

### ISSUE THREAD

**Issue by qxx** [ywu36/IRS---1040NR-with-1099B#1]
对于在美超过183天并且有收入的Nonresident Alien来说，1099-B应该填入Schedule NEC的Line 16而不是Schedule D。这意味着Capital Gain是30%税率并且Capital Loss不能Deduct。

以及根据中美Treaty Article 9，Dividends应该是10%税率。

[Reference](https://www.uscreditcardguide.com/foreigner-investment-tax-guide/)

**Comment by ywu36** [comment]
Hi qxx, thx for your reply. For the 10% tax rate on the dividend, I agree with you. For 1099-B, did you check the original items on the tax law? The tax rate for the foreigner has not been clearly specified. The reference may be wrong. I asked an accountant and he informed me that 30% is applicable, but the capital loss can be deducted and carry on to the next year as for non-resident alien.

**Comment by qxx** [comment]
[Sec 871(a)(2)](https://www.law.cornell.edu/uscode/text/26/871) describes the 183-day rule, the 30% rate and no carryover benefits.

[IRS Pub 519](https://www.irs.gov/pub/irs-pdf/p519.pdf) (page 18) suggests using the Assest-use test and the Business-activities test to determine whether it's effectively connected.

However I'm not a tax professional and the law is written in a way I cannot fully understand. I'm still leaning towards my original opinion, but not 100% sure.

**Comment by ywu36** [comment]
Thanks for your references. I will look into it after the DDL of ECCV2018. Thx.

**Comment by ywu36** [comment]
@qxx 
After look into the guidance (https://www.irs.gov/pub/irs-pdf/p519.pdf) carefully, I guess you are right. Here is the paragraph related to this issue:

'Trading in stocks, securities, and commodities. If your only U.S. business activity is trading in stocks, securities, or commodities (including hedging transactions) through a U.S. resident broker or other agent, **you are not engaged in a trade or business in the United States.** '

This sentence indicates the capital gain from stocks belongs to the incomes that are not effectively connected with US business. So it need to be put into the Schedule NEC. I will update the text soon.

Thank you very much!

Yuhang

**Comment by vc12345679** [comment]
In the conclusion part of [The Taxation of Capital Gains of Nonresident Alien Students, Scholars and Employees of Foreign Governments - www.irs.gov](https://www.irs.gov/individuals/international-taxpayers/the-taxation-of-capital-gains-of-nonresident-alien-students-scholars-and-employees-of-foreign-governments),
> These capital gains would be reported on page 4 (not page 1) of Form 1040NR and would not be reported on a Schedule D because they are being taxed at a flat rate of 30 percent or at a reduced flat rate under a tax treaty..

原文上面一段有 @qxx 提到的183天测试，但是大部分 Non-resident alien 应该都是只能填 schedule NEC，不能填 schedule D。

亲测：TaxAct.com 上不能正确处理，给的是 schedule D；Sprintax.com 上能正确处理，给的是 schedule NEC。

谨供参考
