### ISSUE TITLE
兄弟，你的报税没弄对啊。

### ISSUE THREAD

**Issue by wanghaichao2195** [ywu36/IRS---1040NR-with-1099B#2]
你的股票是不能用schedule d报税的，你需要用schedule nec报税，具体可以看这个link

https://www.irs.gov/individuals/international-taxpayers/the-taxation-of-capital-gains-of-nonresident-alien-students-scholars-and-employees-of-foreign-governments

注意最后一句
These capital gains would be reported on page 4 (not page 1) of Form 1040NR and would not be reported on a Schedule D because they are being taxed at a flat rate of 30 percent or at a reduced flat rate under a tax treaty.

**Comment by wanghaichao2195** [comment]
这里面说的第四页就是schedule nec

**Comment by wanghaichao2195** [comment]
https://www.uscreditcardguide.com/foreigner-investment-tax-guide/?mobile=

**Comment by ywu36** [comment]
Thanks for pointing it out, you're right. I updated the guidance. Thanks!

**Comment by wanghaichao2195** [comment]
ok. no problem.
